### ISSUE TITLE
Does it support using redis as queue?

### ISSUE THREAD

**Issue by Atsman** [onyx-platform/onyx-redis#13]
Hello,

Thanks for plugin!

I want to use redis as a message queue. Carmine library, that you use for communication with redis supports it. It even supports durable queues. So, is it possible to adopt this plugin to support such types of communication with redis? 

[Carmine message queue](https://github.com/ptaoussanis/carmine#message-queue)
[Carmine pub sub](https://github.com/ptaoussanis/carmine#listeners--pubsub)

Thank you,
Aleh

**Comment by gardnervickers** [comment]
Hello Aleh,
We actually did support this a while back but removed it because it was too difficult to provide fault tolerance for reads using the tools Redis provided at the time. I’m out of the loop now when it comes to Redis, but we would need a way to perform reads without consuming the list. I believe there were some ideas around `RPOPLPUSH` and an intermediate “pending reads” list in the past. 

So to answer your question, yes it would be possible. It would be quite easy as long as you don’t care about fault tolerance, but if you need to ensure all your messages are processed, there’s more work involved to composite data structures in Redis to provide a sort-of “transactional read”.

**Comment by Atsman** [comment]
@gardnervickers hey, thank you for answer. So is it right, that i can use this plugin as is, if i am going to use RPOPLPUSH?

**Comment by gardnervickers** [comment]
No, unfortunately this plugin does not support reads from Redis at the moment. I was suggesting an idea for going about fault tolerant reads with using RPOPLPUSH to maintain a pending read list if you wanted to implement Redis reads.

**Comment by Atsman** [comment]
@gardnervickers thank you for explanation, will play with it.
